### ISSUE TITLE
Read access user able to create reports and funnel in rakam UI

### ISSUE THREAD

**Issue by engineerkarthikk** [rakam-io/rakam-ui#116]

**Comment by buremba** [comment]
We have three permission types:
`write permission`: The user will have access to write_key and send the data the API.
`read permission`: The user will be able to query the data using read_key and create new reports, dashboards in Rakam UI.
`master permission`: The user will be able to perform administrative operations on API (creating materialized views etc.) and add new members to the project.

Since it may be confusing, I added the descriptions to team page.
