### ISSUE TITLE
When the dashboard was changed after select some parameters on another one , parameters after "?" stays in link so others dashboard cannot retrieve any data because old  parameters were selected stays in link

### ISSUE THREAD

**Issue by Himmetk** [rakam-io/rakam-ui#28]

**Comment by buremba** [comment]
In fact, the convention is to share the same parameter among dashboards only if it makes sense. Let's say that you have a global _date-range_ parameter and want to share it among the all reports and dashboards similar to how you use Google Analytics. 

The name of date-range parameter should be name in all reports and you should not use that parameter name for any other purpose in order to avoid conflict.

**Comment by Himmetk** [comment]
yes I see your point but if you have many dashboards with different parameters that you cannot apply for all dashboards this feature is just pain. But in such case like applying only existing parameters into another one and ignoring non-exist parameters, then it makes sense. I think.

**Comment by buremba** [comment]
That's the way it currently works. When you visit a dashboard, it just checks the query parameter in order to find out if the value is set for the parameters in that dashboard so the url that you visit may have other query parameters that are not used by the dashboard that you visit.
