### ISSUE TITLE
To be able to use GROUP BY function as a paramaters

### ISSUE THREAD

**Issue by Himmetk** [rakam-io/rakam-ui#35]
When users would like to see detailed breakdown of given reports , it would be good to choose parameters. Like group by function in sql. 

Group by {Paramaters}  I think to do this development first we have to solve select more than one parameters issue.

**Comment by buremba** [comment]
In fact, parameters has nothing to do with GROUP BY statement. Let's say that you wrote a SQL query as follows:
SELECT "{{ dimension }}", count(*) from table GROUP BY 1
You set a default value for dimension chose static possible values. When the user changes the parameter, the dimension will be changed automatically so you get the behaviour you want. 

Please note that I usd {{ }} syntax instead of {}. The reason is that {} converts the variable to SQL literal while {{ }} evaluates the expression inside the statement and results the result. {{ dimension + 'some string' }} is also valid. If you use {} then the compiled SQL would be `SELECT 'dimension', count(*)..` so you won't be able to use the column values.
