### ISSUE TITLE
default dashboard 

### ISSUE THREAD

**Issue by nurkhz** [rakam-io/rakam-ui#37]
after login process it's just a blank page. there should be an action in order to get or see a dashboard etc.

default dashboard could be cool. for instance last updated dashboard can comes first place or last builded one etc.

**Comment by sercanlir** [comment]
Agreeeed

Sent from my mobile. Please excuse the brevity, spelling and punctuation.

On Mar 2, 2017, at 5:54 PM, nurkhz <notifications@github.com<mailto:notifications@github.com>> wrote:


after login process it's just a blank page. there should be an action in order to get or see a dashboard etc.

default dashboard could be cool. for instance last updated dashboard can comes first place or last builded one etc.

**Comment by buremba** [comment]
![image](https://cloud.githubusercontent.com/assets/82745/23515235/9e774f06-ff7a-11e6-8118-62489c1a07f4.png)
