### ISSUE TITLE
There is no way to edit a materialized view after creation on the reports page

### ISSUE THREAD

**Issue by evelant** [rakam-io/rakam-ui#41]
I made a typo in my SQL for a materialized view but after I saved it I could not find a way to open it again for editing. Perhaps the materialized views need to shown on the Reports tab the same way normal reports are?

**Comment by buremba** [comment]
Due the way materialized views work, they can't be edited. Since the data is materialized, any change in data layout would break the materialized view.

However; you can delete and re-create the materialized view with Rakam UI. In report playground page, the sidebar lists the materialized views and when you hover them, you will see an info icon. Clicking that button will create a popover that allows you to see the SQL query of the materialized view and delete it if you need.

**Comment by evelant** [comment]
Ah OK, thank you. I expected to see the materialized views listed in the main Reports tab and did not think to look for that control within the report editor.

**Comment by buremba** [comment]
Reports are related with the UI part but materialized views and continuous queries are actually stored in Rakam API and not related to the UI part, that's why they don't have dedicated page similar to reports page. They allow you to pre-process your data, create summary tables and cache your queries so that your reports can be faster than typical ad-hoc workloads if the data volume is big.
