### ISSUE TITLE
date-range variable does not include the current day when presets are selected

### ISSUE THREAD

**Issue by evelant** [rakam-io/rakam-ui#47]
In reports selecting "Today", "Last Week" etc from the date selector for a date-range type variable does not include data from today. The SQL generated looks like this

```and _time between  cast( '2017-03-09' as date) and  cast( '2017-03-16' as date)```

Today is 03/16/2017 but this query excludes data from today because cast( '2017-03-16' as date) will be compared to timestamps on data as 2017-03-16 00:00:00.

UI should use ```now()``` when these options are selected to include data from the current day.

**Comment by buremba** [comment]
Normally, we use `and _time between {date[0]} and {date[1]} + interval '1' day` but it looks like this is confusing and the most common use case is using the `date-range` variable as part of BETWEEN clause. Since _time is a TIMESTAMP columns,  `cast( '2017-03-16' as date)` will be the start of day so the events occurred in that day won't be be able pass the predicate.

The data range picker can only select dates and AFAIK, `now()` is not in ANSI SQL standard so we can't be sure if the backend database has `now()` procedure. One other workaround is that the system can produce inclusive date range `(cast( '2017-03-09' as date) and cast( '2017-03-17' as date))` but I'm not sure if it removes the confusion.

**Comment by buremba** [comment]
We shift date[1] by one day so `and _time between {date[0]} and {date[1]}` will work as expected now.
