### ISSUE TITLE
Rakam UI fails to process user images when the url doesn't end in a file extension

### ISSUE THREAD

**Issue by huntercarter** [rakam-io/rakam-ui#57]
Rakam UI doesn't seem to work with Facebook image URLs, which do not end in .jpg, .png, etc

Example:

https://scontent.xx.fbcdn.net/v/t1.0-1/p50x50/12002186_10105021916081945_2823494803289488670_n.jpg?oh=c4a9e5e060921efd8ffaeef0f9a5515d&oe=59896470

**Comment by buremba** [comment]
Where is the bug, the picture of the user in people page?

**Comment by huntercarter** [comment]
Yes, Rakam UI doesn't recognize the above link and displays one of the randomly generated avatars instead. I assume this is because the url doesn't end in .jpg

**Comment by buremba** [comment]
Currently we use Gravatar (http://tr.gravatar.com/) for displaying the image of the user. It the email doesn't have an avatar then we generate a random avatar based on the email. We were planning to use a field called `picture_url` for custom avatars, if the value of `picture_url` user attribute exists, we will show that picture in avatar section, otherwise fallback to Gravatar. Does this feature solve your problem?

**Comment by huntercarter** [comment]
Yes. Thanks. When will that feature be released?

**Comment by buremba** [comment]
Thanks for the feedback! We will release the feature this week.

**Comment by huntercarter** [comment]
Awesome. You guys rock.
