### ISSUE TITLE
Delete Report is not working

### ISSUE THREAD

**Issue by Himmetk** [rakam-io/rakam-ui#7]
Reports cannot be deleted. Also, it would be better to have delete button near reports name or some other page to manage reports, remove reports or sharing reports with each others without needing open reports Example from RJ metrics.
![screen shot 2016-12-16 at 11 56 22](https://cloud.githubusercontent.com/assets/24540700/21256944/e62aec38-c37d-11e6-86f7-2754c1ef31ee.png)

**Comment by buremba** [comment]
The delete button is in edit report page so you should press the edit button in reports page in order to be able to remove it. There was a remove button in reports page but in order make it more compact and clean, it moved it. Maybe the way RJMetrics lists the reports is more useful, let me think about it.

**Comment by Himmetk** [comment]
yes, thats what I am doing but still I am not able to remove reports.

**Comment by buremba** [comment]
Ah, I'm able to reproduce the issue now. The issue is fixed and the fix will be deployed to the production in ~24 hours.
