### ISSUE TITLE
Ability find out who is owner of which project

### ISSUE THREAD

**Issue by sambitdixit** [rakam-io/rakam-ui#71]
When i log into Rakam UI as admin, i would like to find out which project is owned by whom so the if i have to disable a project i can ask and follow up with him. I also want to know which report/dashoard/funnel is created by which user. All of this i think we should have a separate page where we can see all these.

**Comment by sambitdixit** [comment]
@buremba did you get a chance to look at this.

**Comment by buremba** [comment]
I added an indicator to /settings/api/team page if the owner of the project is not you. I also added an icon to funnel and retention reports in order to find out the owner of reports.
<img width="258" alt="screen shot 2017-06-10 at 7 31 43 pm" src="https://user-images.githubusercontent.com/82745/27007917-59e15b4c-4e18-11e7-831b-85b2d3fc126f.png">
