### ISSUE TITLE
Labels Cannot be Seen under reports on  Dashboards for Line graph.

### ISSUE THREAD

**Issue by Himmetk** [rakam-io/rakam-ui#9]
Labels  cannot be seen properly within reports on dashboard but  on reports page there is no problem. Also, there are not enough variety of color , if more then 6 segments , same color starts to repeat.

**Comment by buremba** [comment]
Under the chart options, there is an option called "show labels". It activates the labels.

**Comment by Himmetk** [comment]
I meant those dimensions below by saying labels, sorry for confusion. I could not see them in  reports on dashboard.
Thanks :)
![screen shot 2016-12-18 at 23 42 10](https://cloud.githubusercontent.com/assets/24540700/21296367/c4a26d42-c572-11e6-9fa9-fa8b335e02db.png)

**Comment by buremba** [comment]
Do you mean legends? http://www.fusioncharts.com/dev/assets/images/legend.png.pagespeed.ce.g-4XnLQKdw.png

Legends are enabled by default if you disable the table. Since the table columns are similar to the way the legend mechanism is used, I did not put an extra config for it. If you click the colorful circles in table, you can toggle the series in the chart.

**Comment by Himmetk** [comment]
yes , but sometimes we have to send screenshot, that's why it would be better to be able to see legends below for classical charts (line,bar, pie etc.).
